site_name: Conreq Documentation

nav:
  - Home: index.md
  - Configuration:
      - Organizr Authentication: organizr.md
      - MySQL: mysql.md
  - Development:
      - Our Code Explained: code_tldr.md
      - Building Conreq: building.md
      - Making Extensions: extensions.md
      - Updating the Docs: docs_contrib.md

theme:
  name: material
